name: CommitWebSite
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0      
      - name: get the latest change
        run: |
          echo $(date +"%d.%m.%Y %H:%M:%S"; git log -n 1 --skip=1 | grep Author | sed -e s/^Author:\ /\ /; git diff $(git log -n 1 --skip=1 | grep "commit" | awk -F' '  '{print $2}') | grep '^[+-][+-][+-]' | head -1 | awk -F' ' '{print $2}' | sed -e s/^[ab].//)
          for i in $(ls -1 content/diagrams) ; do mkdir -p content/docs/diagrams/$i ; cp content/diagrams/$i content/docs/diagrams/$i ; printf "\n---\ntitle: $i\ndate: 2017-10-17T15:26:15Z\nbookToc: false\n---\n\n{{<bpmnviewer>}}$i{{</bpmnviewer>}}\n" > content/docs/diagrams/$i/_index.md ; done
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.68.3"      
      - name: Build
        run: hugo --minify      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HUGO }}
          external_repository: isrcloudchallenge/emmenflo.github.io
          publish_dir: ./public
          keep_files: true
          user_name: isrcloudchallenge
          user_email: martin.jahr@isr.de
          publish_branch: main
          cname: emmenflo.selfscrum.org