name: CommitWebSite
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0      
      - name: get the latest change
        run: |
          mkdir -p content/docs/diagrams
          printf "\n---\ntitle: Alle Diagramme\ndate: 2017-10-17T15:26:15Z\nbookToc: false\nbookCollapseSection: true\n---\n\n# Alle Diagramme\n\n" > content/docs/diagrams/_index.md
          for i in $(ls -1 content/diagrams) ; do printf "* [$i](./$i)\n" >> content/docs/diagrams/_index.md ; mkdir -p content/docs/diagrams/$i ; cp content/diagrams/$i content/docs/diagrams/$i ; printf "\n---\ntitle: $i\ndate: 2017-10-17T15:26:15Z\nbookToc: false\n---\n\n# $i\n\n{{<bpmnviewer>}}$i{{</bpmnviewer>}}\n" > content/docs/diagrams/$i/_index.md ; done
          mkdir -p content/docs/images
          printf "\n---\ntitle: Alle Bilder\ndate: 2017-10-17T15:26:15Z\nbookToc: false\nbookCollapseSection: true\n---\n\n# Alle Bilder\n\n" > content/docs/images/_index.md
          for i in $(ls -1 content/images) ; do printf "* [$i](./$i)\n" >> content/docs/images/_index.md ; mkdir -p content/docs/images/$i ; cp content/images/$i content/docs/images/$i ; printf "\n---\ntitle: $i\ndate: 2017-10-17T15:26:15Z\nbookToc: false\n---\n\n# $i\n\n![]($i)\n" > content/docs/images/$i/_index.md ; done
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.68.3"      
      - name: Build
        run: hugo --minify      
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HUGO }}
          external_repository: isrcloudchallenge/emmenflo.github.io
          publish_dir: ./artifacts/public
          keep_files: false
          user_name: isrcloudchallenge
          user_email: martin.jahr@isr.de
          publish_branch: main
          cname: emmenflo.selfscrum.org